name: Update README with Recent Activity

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README
    steps:
      - uses: Readme-Workflows/recent-activity@v2.2.0
        with:
          CONFIG_FILE: .github/activity-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

